# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install python-pushsafer
        pip install chromedriver-autoinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: open main.py
      run: |
        # stop the build if there are Python syntax errors or undefined names
        main.py
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide

