name: run main.py

on:
  schedule:
    - cron: '* * * * *' # At 5min o

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install chromedriver-autoinstaller
          pip install python-pushsafer
          pip install selenium
          
      - name: execute py script # run main.py

        run: python main.py
          
 
